# Anàlisi general taules de dades csv PADRIS

In [2]:
import pandas as pd
import numpy as np
import random as rd

## 1. Taula 5 Derivació dels pacients

In [4]:
path = r'C:\Users\LRAJAG\Desktop\DATOS_PADRIS_nets\689_F_ap_derivacio_sm_Final.csv'
df_derivacio = pd.read_csv(path)

In [5]:
df_derivacio.head()

,id,idCas,Identificador de registre CMBD,Unitat Proveïdora,UP_descripcio,Data inici assistència,Tipus de professional,Tipus_professional_descrip,Unitat Proveïdora Destí,Tipus UP Destí
0,1,83892072,263736108,337,EAP Baix Berguedà,3/27/2015,1,1 Metge/ssa de família,CSM Adults Berguedà,ASSISTÈNCIA SALUT MENTAL - AMBULATÒRIA
1,2,83892237,306747946,1933,EAP Barcelona 7B - Sardenya,10/21/2015,1,1 Metge/ssa de família,CSM Adults Guinardó,ASSISTÈNCIA SALUT MENTAL - AMBULATÒRIA
2,3,83897885,250764528,294,EAP Badalona 3 - Progrés-Raval,1/8/2015,1,1 Metge/ssa de família,CSM Adults Badalona 1 Est,ASSISTÈNCIA SALUT MENTAL - AMBULATÒRIA
3,4,83900256,278190986,157,EAP Garraf Rural,7/9/2015,1,1 Metge/ssa de família,CSM Garraf,ASSISTÈNCIA SALUT MENTAL - AMBULATÒRIA
4,5,83902712,257236651,1798,EAP Palamós,2/19/2015,2,2 Pediatre/a,CSM Adults Baix Empordà,ASSISTÈNCIA SALUT MENTAL - AMBULATÒRIA

In [6]:
df_derivacio.Tipus_professional_descrip.unique()

array(['1 Metge/ssa de família', '2 Pediatre/a', '4 Infermer/a',
       '3 Odontòleg/oga', '5 Treballador/a social'], dtype=object)

In [7]:
df_derivacio["Tipus de professional"].unique()

array([1, 2, 4, 3, 5])

In [8]:
df_derivacio.id.count()

np.int64(7195)

## 2. Tabac

VAL:
- 0= No fumador 
- 1= Fumador 
- 2 = exfumador

In [9]:
df_tabac=pd.read_csv(r"C:\Users\LRAJAG\Desktop\DATOS_PADRIS_nets\8_tabac_cohort_total_Final.csv")
df_tabac.head()

   id     idCas                       DAT                    DBAIXA  VAL
0   1  73405423  2012-11-12T22:00:00.000Z  2017-12-30T22:00:00.000Z    0
1   2  73405425  2016-06-08T20:00:00.000Z  2017-12-30T22:00:00.000Z    0
2   3  73405429  2016-10-23T20:00:00.000Z  2017-12-30T22:00:00.000Z    0
3   4  73405436  2017-03-05T22:00:00.000Z  2017-12-30T22:00:00.000Z    0
4   5  78465847  2017-11-07T22:00:00.000Z  2017-12-30T22:00:00.000Z    0

In [10]:
df_tabac.VAL.unique()

array([0, 2, 1])

### Columnes triades: 'VAL'

## Fàrmacs Dispensats

### OF (Oficina de farmàcia)
23_farmacs_dispensants_2010_2019_Final

In [ ]:
cols_dispensats = [
    'idCas', 
    'Any_Mes', 
    'ID_HIS_Subgrup_7_ATC', 
    'ID_HIS_Forma_Farmaceutica', 
    'DES_HIS_Producte',
    'Nombre_Envasos_Dispensats'
]

df_disp = pd.read_csv(
    r"C:\Users\LRAJAG\Desktop\DATOS_PADRIS_nets\23_farmacs_dispensants_2010_2019_Final.csv", 
    sep=',', 
    encoding='latin1', 
    usecols=cols_dispensats
)

In [14]:
df_disp.head()

,idCas,Any_Mes,ID_HIS_Subgrup_7_ATC,DES_HIS_Producte,ID_HIS_Forma_Farmaceutica,Nombre_Envasos_Dispensats
0,68121038,201912,N05BA06,LORAZEPAM NORMON 1MG 50 COMPRIMIDOS EFG,CO,1
1,68121038,201912,N05CF02,ZOLPIDEM NORMON 10MG 30 COMPRIMIDOS RECUB EFG,CO,1
2,68121038,201912,N05AX12,ABILIFY 10MG 28 COMPRIMIDOS,CO,2
3,68121038,201912,N03AE01,RIVOTRIL 2MG 60 COMPRIMIDOS,CO,1
4,68121038,201912,N06AB06,SERTRALINA NORMON 100MG 30 COMP RECUB PELIC EFG,CO,1

### MHDA (Hospital)
Seleccionar mateixes columnes que farmacs OF però afegim pas de treure pacients amb idCas dins de cohort_control.
Pel futur merge amb farmacs_dispensats afegim columna d'envasos que és majoritàriament 1.

In [24]:
cols_indices = [1, 2, 3, 5, 8]

df_mhda = pd.read_csv(
    r"C:\Users\LRAJAG\Desktop\DATOS_PADRIS_nets\25_taula_farmacs_mhda_2010_2019_Final.csv", 
    sep=',', 
    encoding='latin1', 
    usecols=cols_indices
)

# Ara que ja les hem carregat, els canviem el nom a un format fàcil
df_mhda.columns = [
    'idCas', 
    'Any_Mes', 
    'ID_HIS_Subgrup_7_ATC', 
    'ID_HIS_Forma_Farmaceutica', 
    'DES_HIS_Producte'
]

# Recordem afegir la columna d'envasos que a MHDA no hi és
df_mhda['Nombre_Envasos_Dispensats'] = 1

print("MHDA carregat correctament fent servir índexs!")
print(df_mhda.head())

MHDA carregat correctament fent servir índexs!
      idCas  Any_Mes ID_HIS_Subgrup_7_ATC ID_HIS_Forma_Farmaceutica  \
0  68076528   201912              J05AR03                        CO
1  68076528   201912              J05AX08                        CO
2  69435259   201911              J05AR20                        CO
3  69435259   201912              J05AR20                        CO
4  69575889   201911              B03XA02                        IJ

                                    DES_HIS_Producte  \
0  EMTRICITABINA/TENOFOVIR DISOPROXILO TEVA 200/2...
1  ISENTRESS 400MG 60 COMPRIMIDOS RECUBIERTOS CON...
2  BIKTARVY 50/200/25MG 30 COMPRIMIDOS RECUBIERTO...
3  BIKTARVY 50/200/25MG 30 COMPRIMIDOS RECUBIERTO...
4  ARANESP 40MCG SOLUCION INYECTABLE 4 JER PRC C/...

   Nombre_Envasos_Dispensats
0                          1
1                          1
2                          1
3                          1
4                          1

Faig primer df_disp_estudi perquè hi ha 67 milions d'entrades de dades

In [ ]:
# 1. Carreguem els IDs 
ids_estudi = pd.read_csv(r"C:\Users\LRAJAG\Desktop\DATOS_PADRIS_nets\3_taula_0_cohort_estudi_Final.csv")['idCas'].unique()

# 2. Preparem la lectura per "chunks"
ruta_disp = r"C:\Users\LRAJAG\Desktop\DATOS_PADRIS_nets\23_farmacs_dispensants_2010_2019_Final.csv"
cols_disp = ['idCas', 'Any_Mes', 'ID_HIS_Subgrup_7_ATC', 'ID_HIS_Forma_Farmaceutica', 'DES_HIS_Producte', 'Nombre_Envasos_Dispensats']

# Creem una llista on anirem guardant els trossos filtrats
llista_trossos_filtrats = []

print("Començant a processar els 67 milions de files per trossos...")

# Llegim el fitxer de 1 milió en 1 milió de files
for chunk in pd.read_csv(ruta_disp, sep=',', encoding='latin1', usecols=cols_disp, chunksize=1000000):
    # Filtrem el tros actual: només els de l'estudi
    tros_filtrat = chunk[chunk['idCas'].isin(ids_estudi)]
    
    # Si el tros té dades que ens interessen, el guardem
    if not tros_filtrat.empty:
        llista_trossos_filtrats.append(tros_filtrat)

# Unim tots els trossos filtrats en un sol DataFrame (molt més petit!)
df_disp_estudi = pd.concat(llista_trossos_filtrats, ignore_index=True)

print(f"Fet! Ara df_disp_estudi només ocupa la memòria dels teus pacients d'estudi.")

: